version: "2"
services:
  mysql:
    image: mysql:8.0.1
    container_name: dev_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema
    volumes:
      - data-volume:/var/lib/mysql
  phpadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8004:80"
    restart: always
    depends_on:
      - mysql

volumes:
  data-volume:
