import Vue from 'vue';
import Vuex from 'vuex';
import { SET_ROOM, SET_SOCKET_STATE, SET_USER } from './mutation-types';

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    socketConnected: false,
    player: {
      username: 'autoGenerated',
    },
    room: null,
  },
  mutations: {
    [SET_USER](state, payload) {
      this.state.player = payload;
    },
    [SET_ROOM](state, payload) {
      this.state.room = payload;
    },
    [SET_SOCKET_STATE](state, payload) {
      this.state.socketConnected = payload.isConnected;
    },
  },
  actions: {

  },
  getters: {
    room: state => state.room,
    sessionID: state => state.player.sessionID,
    username: state => state.player.username,
    isSocketConnected: state => state.socketConnected,
    roomAdminID: state => state.room.adminSessionID,
    isRoomRunning: state => (state.room ? state.room.running : false),
    isRoomAdmin: state => state.room.adminSessionID === state.player.sessionID,
  },
});
