import Vue from 'vue';
import Vuex from 'vuex';
import { SET_ROOM, SET_SOCKET_STATE, SET_USERNAME } from './mutation-types';

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    socketConnected: false,
    room: null,
    username: 'autoGenerated',
  },
  mutations: {
    [SET_USERNAME](state, payload) {
      this.state.username = payload.username;
    },
    [SET_ROOM](state, payload) {
      this.state.room = payload;
    },
    [SET_SOCKET_STATE](state, payload) {
      this.state.socketConnected = payload.isConnected;
    },
  },
  actions: {

  },
  getters: {
    roomID: state => (state.room ? state.room.id : null),
    username: state => state.user,
    isSocketConnected: state => state.socketConnected,
  },
});
