import Vue from 'vue';
import Vuex from 'vuex';
import { SET_ROOM_ID, SET_USERNAME } from './mutation-types';

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    roomID: null,
    username: 'autoGenerated',
  },
  mutations: {
    [SET_USERNAME](state, payload) {
      this.state.username = payload.username;
    },
    [SET_ROOM_ID](state, payload){
      this.state.roomID = payload.roomID;
    },
  },
  actions: {

  },
  getters: {
    roomID: state => state.roomID,
    username: state => state.user,
  },
});
